name: Wave on multiple platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        build_type: [ Release ]
        c_compiler: [ gcc, clang, cl ]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
          - os: macOS-latest
            c_compiler: clang
            cpp_compiler: clang++
          - os: macOS-latest
            c_compiler: gcc
            cpp_compiler: g++
        exclude:
          - os: ubuntu-latest
            c_compiler: cl
          - os: macOS-latest
            c_compiler: cl
    steps:
      - uses: actions/checkout@v3

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Configure CMake
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DWAVE_BUILD_EXAMPLES=OFF
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: 'wave-${{ matrix.os }}-${{ matrix.c_compiler }}'
          path: ${{ steps.strings.outputs.build-output-dir }}
          if-no-files-found: 'warn'
          retention-days: 30
          compression-level: 6
          overwrite: false